var pg = require('pg');
var charData = '';
var config = {
  user: process.env.DBUSER,
  database: 'dfdh0vcuqbbj7u',
  password: process.env.DBPWD,
  host: 'ec2-54-235-77-0.compute-1.amazonaws.com',
  port: 5432,
  max: 10,
  idleTimeoutMillis: 50000,
  ssl: true,
};

var pool = new pg.Pool(config);

exports.run = (client, message, args) => {
    insertData(message)
    message.channel.send("Character Uploaded" + charData).catch(console.error);
}

function insertData(message){
  let fullCommand = message.content
  let splitCommand = fullCommand.split(" ") // Split the message up in to pieces for each space
  let primaryCommand = splitCommand[0] // isolate command
  let arguments = splitCommand.slice(1) // // All other words are arguments/parameters/options for the command
  console.log("Command received: " + primaryCommand)
  console.log("Arguments: " + arguments)
}

pool.connect( (err, client, done) => {
        if(err) {
          console.log(err)
        }else
        client.query('create table if not exists dndchars( \
            id int generated by default as identity primary key , \
            name text, \
            race text, \
            type text, \
            level integer default 1, \
            proficiency integer default 0, \
            strength integer default 0, \
            dexterity integer default 0, \
            constitution integer default 0, \
            wisdom integer default 0, \
            charisma integer default 0, \
            hp integer default 0, \
            initiative integer default 0, \
            armor integer default 0, \
            speed integer default 0, \
            skills text, \
            p_l text, \
            senses text, \
            defenses text, \
            conditions text, \
            actions text, \
            equipment text, \
            features text, \
            creatures text)', (err, result) => {
                //disconnent from database on error
                done();
                if (err) {
                        throw err;
                }
            client.query('INSERT INTO dndchars(name, race, type, level) VALUES (\'Findwilas\', \'Half-Elf\', \'Ranger\', 1)')
            charData = client.query('select * from dndchars')
        });
});
